# Modern Docker Compose - no version field needed
services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: project-service-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: project_service_dev
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_user -d project_service_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: project-service-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
  redis_data: